# This is a GitHub workflow YAML file
# see https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
#
# If you want to update this file it's recommended to use a YAML validator
# https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml
# configured to validate with https://json.schemastore.org/github-workflow.json
#
# This workflow is responsible to perform various checks related to the codebase,
# For every push to main or on a pull request, it
# - ensures there is no eslint error on files
# - ensures there is no test failing
# - uploads code coverage from tests to codecov
#
# If all these steps are passing and there is a secrets.NPM_TOKEN and version in package.json
# is not already published, workflow published the package on npm.

name: main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15, windows-2022]
        node: [16.13.0]
    runs-on: ${{ matrix.os }}
    name: test on ${{ matrix.os }} and node ${{ matrix.node }}
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install node modules
        run: npm install
      - name: Generate importmap
        run: npm run importmap
      - name: Run ESLint
        run: npm run eslint
      - name: Run tests
        env:
          GITHUB_TOKEN: ${{ secrets.TEST_GITHUB_TOKEN }} # to test publish package on github registry
        run: npm run test-with-coverage
      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./packages/jsenv-github-pull-request-impact/coverage/coverage.json,./packages/jsenv-github-release-package/coverage/coverage.json,./packages/jsenv-package-publish/coverage/coverage.json
          verbose: true
